import tseslint from "typescript-eslint";

export default [
  {
    ignores: [
      "node_modules/",
      "dist/",
      "**/.zfb/",
      "**/.zfb-build/",
      "**/.zudo-doc/",
      "worktrees/",
      ".wrangler/",
      "**/.vitest/",
    ],
  },
  ...tseslint.configs.recommended.map((config) => ({
    ...config,
    files: ["**/*.ts", "**/*.tsx"],
  })),
  {
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/consistent-type-imports": ["error", { prefer: "type-imports" }],
      "@typescript-eslint/no-explicit-any": "warn",
      "no-console": "warn",
      "prefer-const": "error",
      "no-var": "error",
      "prefer-template": "error",
    },
  },
  {
    files: ["packages/core/src/**/*.ts", "packages/core/src/**/*.tsx"],
    rules: {
      // Core is shared with workerd and the Rust-side implementation. Keep
      // its imports limited to ES and Web-standard APIs.
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["node:*"],
              message: "packages/core must not depend on Node.js built-ins.",
            },
            {
              group: [
                "_http_*",
                "_stream_*",
                "_tls_*",
                "assert",
                "assert/*",
                "async_hooks",
                "buffer",
                "child_process",
                "cluster",
                "console",
                "constants",
                "crypto",
                "dgram",
                "diagnostics_channel",
                "dns",
                "dns/*",
                "domain",
                "events",
                "fs",
                "fs/*",
                "http",
                "http/*",
                "http2",
                "https",
                "inspector",
                "inspector/*",
                "module",
                "net",
                "os",
                "path",
                "path/*",
                "perf_hooks",
                "process",
                "punycode",
                "querystring",
                "readline",
                "readline/*",
                "repl",
                "sea",
                "sqlite",
                "stream",
                "stream/*",
                "string_decoder",
                "sys",
                "test",
                "test/*",
                "timers",
                "timers/*",
                "tls",
                "trace_events",
                "tty",
                "url",
                "util",
                "util/*",
                "v8",
                "vm",
                "wasi",
                "worker_threads",
                "zlib",
              ],
              message: "packages/core must not depend on Node.js built-ins.",
            },
          ],
        },
      ],
    },
  },
  { files: ["scripts/**", "**/*.test.ts"], rules: { "no-console": "off" } },
  { files: ["**/vitest.global-setup.ts"], rules: { "no-console": "off" } },
];
