/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=PublicEnv src/worker-configuration.d.ts` (hash: a16bd69989b0656f811e34012b45af1a)
interface __BaseEnv_PublicEnv {
  ARTIFACTS: R2Bucket;
  PUBLIC_BASE_DOMAIN: string;
  CONTROL:
    | Service /* entrypoint PublicationResolver from zudo-ez-host-control-staging */
    | Service /* entrypoint PublicationResolver from zudo-ez-host-control */
    | Service /* entrypoint PublicationResolver from zudo-ez-host-control-local */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface StagingEnv {
    ARTIFACTS: R2Bucket;
    PUBLIC_BASE_DOMAIN: string;
    CONTROL: Service /* entrypoint PublicationResolver from zudo-ez-host-control-staging */;
  }
  interface ProductionEnv {
    ARTIFACTS: R2Bucket;
    PUBLIC_BASE_DOMAIN: string;
    CONTROL: Service /* entrypoint PublicationResolver from zudo-ez-host-control */;
  }
  interface Env extends __BaseEnv_PublicEnv {}
}
interface PublicEnv extends __BaseEnv_PublicEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_BASE_DOMAIN">> {}
}
