/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=PublicEnv src/worker-configuration.d.ts` (hash: 2dfca7a3874a20e42ce0cabe52961723)
interface __BaseEnv_PublicEnv {
  ARTIFACTS: R2Bucket;
  PUBLIC_BASE_DOMAIN: "public.test";
  CONTROL: Service /* entrypoint PublicationResolver from zudo-ez-host-control-local */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_PublicEnv {}
}
interface PublicEnv extends __BaseEnv_PublicEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_BASE_DOMAIN">> {}
}
