/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=PublicEnv src/worker-configuration.d.ts` (hash: 0578efab593873fb6d9615128d80ace6)
interface __BaseEnv_PublicEnv {
  ARTIFACTS: R2Bucket;
  CONTROL: Service /* entrypoint PublicationResolver from zudo-ez-host-control-local */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_PublicEnv {}
}
interface PublicEnv extends __BaseEnv_PublicEnv {}
