/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=ControlEnv src/worker-configuration.d.ts` (hash: fd3367f3d6b92b5349cd155db14ce52f)
interface __BaseEnv_ControlEnv {
  ARTIFACTS: R2Bucket;
  DB: D1Database;
  BETTER_AUTH_BASE_URL: "https://control.test";
  BETTER_AUTH_TRUSTED_ORIGINS: "https://control.test";
  PUBLICATION_RESOLVER: Service<typeof import("./index").PublicationResolver>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_ControlEnv {}
}
interface ControlEnv extends __BaseEnv_ControlEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "BETTER_AUTH_BASE_URL" | "BETTER_AUTH_TRUSTED_ORIGINS">
  > {}
}
