/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=ControlEnv src/worker-configuration.d.ts` (hash: af3b64dcfd0cb6a624484e123f6978f2)
interface __BaseEnv_ControlEnv {
  ARTIFACTS: R2Bucket;
  DB: D1Database;
  PUBLICATION_RESOLVER: Service<typeof import("./index").PublicationResolver>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_ControlEnv {}
}
interface ControlEnv extends __BaseEnv_ControlEnv {}
