/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=ControlEnv src/worker-configuration.d.ts` (hash: 7588243187071e318f95f8957754dfcc)
interface __BaseEnv_ControlEnv {
  ARTIFACTS: R2Bucket;
  DB: D1Database;
  BETTER_AUTH_BASE_URL: string;
  BETTER_AUTH_TRUSTED_ORIGINS: string;
  CONTROL_BASE_DOMAIN?: string;
  PUBLIC_BASE_DOMAIN?: string;
  R2_ACCOUNT_ID?: string;
  R2_BUCKET_NAME?: string;
  BETTER_AUTH_SECRET?: string;
  SIGNUP_ALLOWED_EMAILS?: string;
  R2_ACCESS_KEY_ID?: string;
  R2_SECRET_ACCESS_KEY?: string;
  PUBLICATION_RESOLVER?: Service<typeof import("./index").PublicationResolver>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface StagingEnv {
    ARTIFACTS: R2Bucket;
    DB: D1Database;
    BETTER_AUTH_BASE_URL: string;
    BETTER_AUTH_TRUSTED_ORIGINS: string;
    CONTROL_BASE_DOMAIN: string;
    PUBLIC_BASE_DOMAIN: string;
    R2_ACCOUNT_ID: string;
    R2_BUCKET_NAME: string;
    BETTER_AUTH_SECRET: string;
    SIGNUP_ALLOWED_EMAILS: string;
    R2_ACCESS_KEY_ID: string;
    R2_SECRET_ACCESS_KEY: string;
  }
  interface ProductionEnv {
    ARTIFACTS: R2Bucket;
    DB: D1Database;
    BETTER_AUTH_BASE_URL: string;
    BETTER_AUTH_TRUSTED_ORIGINS: string;
    CONTROL_BASE_DOMAIN: string;
    PUBLIC_BASE_DOMAIN: string;
    R2_ACCOUNT_ID: string;
    R2_BUCKET_NAME: string;
    BETTER_AUTH_SECRET: string;
    SIGNUP_ALLOWED_EMAILS: string;
    R2_ACCESS_KEY_ID: string;
    R2_SECRET_ACCESS_KEY: string;
  }
  interface Env extends __BaseEnv_ControlEnv {}
}
interface ControlEnv extends __BaseEnv_ControlEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "BETTER_AUTH_BASE_URL"
      | "BETTER_AUTH_TRUSTED_ORIGINS"
      | "CONTROL_BASE_DOMAIN"
      | "PUBLIC_BASE_DOMAIN"
      | "R2_ACCOUNT_ID"
      | "R2_BUCKET_NAME"
      | "BETTER_AUTH_SECRET"
      | "SIGNUP_ALLOWED_EMAILS"
      | "R2_ACCESS_KEY_ID"
      | "R2_SECRET_ACCESS_KEY"
    >
  > {}
}
